name: Test and Analyse
on:
  pull_request:
    types: [ opened,reopened,edited ]
    branches:
      - dev

jobs:
  test_and_analyse:
    name: Test and Analyse
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install requirements
        run: |
          sudo apt update  &>/dev/null
          sudo apt install -y wget jq zip maven gnupg2  &>/dev/null

      - name: Prepare test environment
        env:
          TEST_ENV: ${{ secrets.TEST_ENV }}
        run: |
          echo $TEST_ENV | base64 -d > src/test/resources/testEnvironment.json
          ls src/test/resources/

      - name: Prepare build environment
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
          GPG_TRUST: ${{ secrets.GPG_TRUST }}
          GPG_PASS_PHRASE: ${{ secrets.GPG_PASS_PHRASE }}
          MAVEN_SETTINGS: ${{ secrets.MAVEN_SETTINGS }}
        run: |
          echo $GPG_KEY | base64 -d > private.gpg
          echo $GPG_PASS_PHRASE > gpg2 --import --batch private.gpg
          echo $GPG_TRUST | base64 -d > trust.gpg && echo gpg2 --import-ownertrust trust.gpg
          [ -d "$HOME/.m2" ] || mkdir $HOME/.m2
          echo $MAVEN_SETTINGS | base64 -d > settings.xml
            

      - name: Test and analyse
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          mvn clean verify
          

          


